// <auto-generated />
using BGVC.Airline.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BGVC.Airline.Backend.Migrations
{
    [DbContext(typeof(AirlineDBContext))]
    [Migration("20190312190824_Airline_Seeding_Countries")]
    partial class Airline_Seeding_Countries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BGVC.Airline.Backend.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BGVC.Airline.Backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bolivia, Plurinational State of"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 33,
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Congo, the Democratic Republic of the"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 76,
                            Name = "France"
                        },
                        new
                        {
                            Id = 77,
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 78,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 103,
                            Name = "India"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Macedonia, the Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 158,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Palestine, State of"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 193,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 201,
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = 202,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 206,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 207,
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 208,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 209,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 234,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 235,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 236,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 237,
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 240,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Venezuela, Bolivarian Republic of"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 245,
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 246,
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 247,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 249,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BGVC.Airline.Backend.Models.City", b =>
                {
                    b.HasOne("BGVC.Airline.Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
