// <auto-generated />
using BGVC.Airline.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BGVC.Airline.Backend.Migrations
{
    [DbContext(typeof(AirlineDBContext))]
    [Migration("20190314012930_20190314022800_Airline_Seeding_Countries_Correction")]
    partial class _20190314022800_Airline_Seeding_Countries_Correction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BGVC.Airline.Backend.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BGVC.Airline.Backend.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Iso")
                        .HasMaxLength(2);

                    b.Property<string>("Iso3")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .HasMaxLength(64);

                    b.Property<string>("NumCode")
                        .HasMaxLength(3);

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(4);

                    b.Property<string>("PrintableName")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Iso = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Iso = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            Iso = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Iso = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Iso = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Iso = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Iso = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Iso = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Iso = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Iso = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Iso = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Iso = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Iso = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Iso = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Iso = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Iso = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Iso = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Iso = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 19,
                            Iso = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Iso = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Iso = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Iso = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Iso = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Iso = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Iso = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Iso = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Iso = "BO",
                            Name = "Bolivia, Plurinational State of"
                        },
                        new
                        {
                            Id = 28,
                            Iso = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 29,
                            Iso = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Iso = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Iso = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            Iso = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 33,
                            Iso = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            Iso = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 35,
                            Iso = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Iso = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Iso = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Iso = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            Iso = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            Iso = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            Iso = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 42,
                            Iso = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            Iso = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            Iso = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Iso = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            Iso = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            Iso = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48,
                            Iso = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49,
                            Iso = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            Iso = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51,
                            Iso = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52,
                            Iso = "CD",
                            Name = "Congo, the Democratic Republic of the"
                        },
                        new
                        {
                            Id = 53,
                            Iso = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54,
                            Iso = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            Iso = "CI",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 56,
                            Iso = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57,
                            Iso = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 58,
                            Iso = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 59,
                            Iso = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 60,
                            Iso = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 61,
                            Iso = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62,
                            Iso = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            Iso = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64,
                            Iso = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            Iso = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66,
                            Iso = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67,
                            Iso = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68,
                            Iso = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69,
                            Iso = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70,
                            Iso = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            Iso = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72,
                            Iso = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 73,
                            Iso = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 74,
                            Iso = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 75,
                            Iso = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 76,
                            Iso = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 77,
                            Iso = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 78,
                            Iso = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 79,
                            Iso = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 80,
                            Iso = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 81,
                            Iso = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 82,
                            Iso = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 83,
                            Iso = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 84,
                            Iso = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 85,
                            Iso = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 86,
                            Iso = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 87,
                            Iso = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 88,
                            Iso = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 89,
                            Iso = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 90,
                            Iso = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 91,
                            Iso = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 92,
                            Iso = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 93,
                            Iso = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 94,
                            Iso = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 95,
                            Iso = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 96,
                            Iso = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 97,
                            Iso = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 98,
                            Iso = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 99,
                            Iso = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 100,
                            Iso = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 101,
                            Iso = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 102,
                            Iso = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 103,
                            Iso = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 104,
                            Iso = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 105,
                            Iso = "IR",
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            Id = 106,
                            Iso = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 107,
                            Iso = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 108,
                            Iso = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 109,
                            Iso = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 110,
                            Iso = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 111,
                            Iso = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 112,
                            Iso = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 113,
                            Iso = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 114,
                            Iso = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 115,
                            Iso = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 116,
                            Iso = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 117,
                            Iso = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 118,
                            Iso = "KP",
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            Id = 119,
                            Iso = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 120,
                            Iso = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            Iso = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            Iso = "LA",
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 123,
                            Iso = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            Iso = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            Iso = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            Iso = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            Iso = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            Iso = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            Iso = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            Iso = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            Iso = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 132,
                            Iso = "MK",
                            Name = "Macedonia, the Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 133,
                            Iso = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 134,
                            Iso = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 135,
                            Iso = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 136,
                            Iso = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 137,
                            Iso = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 138,
                            Iso = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 139,
                            Iso = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 140,
                            Iso = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 141,
                            Iso = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 142,
                            Iso = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 143,
                            Iso = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 144,
                            Iso = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 145,
                            Iso = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 146,
                            Iso = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 147,
                            Iso = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 148,
                            Iso = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 149,
                            Iso = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 150,
                            Iso = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 151,
                            Iso = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 152,
                            Iso = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 153,
                            Iso = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 154,
                            Iso = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 155,
                            Iso = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 156,
                            Iso = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 157,
                            Iso = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 158,
                            Iso = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 159,
                            Iso = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 160,
                            Iso = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 161,
                            Iso = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 162,
                            Iso = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            Iso = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 164,
                            Iso = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 165,
                            Iso = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 166,
                            Iso = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 167,
                            Iso = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 168,
                            Iso = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 169,
                            Iso = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 170,
                            Iso = "PS",
                            Name = "Palestine, State of"
                        },
                        new
                        {
                            Id = 171,
                            Iso = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 172,
                            Iso = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 173,
                            Iso = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 174,
                            Iso = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 175,
                            Iso = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 176,
                            Iso = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 177,
                            Iso = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 178,
                            Iso = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 179,
                            Iso = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 180,
                            Iso = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 181,
                            Iso = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 182,
                            Iso = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 183,
                            Iso = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 184,
                            Iso = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 185,
                            Iso = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 186,
                            Iso = "SH",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = 187,
                            Iso = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 188,
                            Iso = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 189,
                            Iso = "MF",
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = 190,
                            Iso = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 191,
                            Iso = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 192,
                            Iso = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 193,
                            Iso = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 194,
                            Iso = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 195,
                            Iso = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 196,
                            Iso = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            Iso = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 198,
                            Iso = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            Iso = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 200,
                            Iso = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 201,
                            Iso = "SX",
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = 202,
                            Iso = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 203,
                            Iso = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 204,
                            Iso = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 205,
                            Iso = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 206,
                            Iso = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 207,
                            Iso = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 208,
                            Iso = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 209,
                            Iso = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 210,
                            Iso = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 211,
                            Iso = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 212,
                            Iso = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 213,
                            Iso = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 214,
                            Iso = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 215,
                            Iso = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 216,
                            Iso = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 217,
                            Iso = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 218,
                            Iso = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = 219,
                            Iso = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 220,
                            Iso = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 221,
                            Iso = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 222,
                            Iso = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 223,
                            Iso = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 224,
                            Iso = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 225,
                            Iso = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 226,
                            Iso = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 227,
                            Iso = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 228,
                            Iso = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 229,
                            Iso = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 230,
                            Iso = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 231,
                            Iso = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 232,
                            Iso = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 233,
                            Iso = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 234,
                            Iso = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 235,
                            Iso = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 236,
                            Iso = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 237,
                            Iso = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 238,
                            Iso = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 239,
                            Iso = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 240,
                            Iso = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 241,
                            Iso = "VE",
                            Name = "Venezuela, Bolivarian Republic of"
                        },
                        new
                        {
                            Id = 242,
                            Iso = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 243,
                            Iso = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 244,
                            Iso = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 245,
                            Iso = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 246,
                            Iso = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 247,
                            Iso = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 248,
                            Iso = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 249,
                            Iso = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BGVC.Airline.Backend.Models.City", b =>
                {
                    b.HasOne("BGVC.Airline.Backend.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
