using BGVC.Airline.Backend.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BGVC.Airline.Backend
{
    public class AirlineDBContext : DbContext
    {
        public AirlineDBContext(DbContextOptions<AirlineDBContext> options) : base(options)
        {
            Database.Migrate();
        }

        public DbSet<Country> Countries { get; set; }
        public DbSet<IsoRegion> IsoRegions { get; set; }
        public DbSet<Municipality> Municipalities { get; set; }
        public DbSet<AirportType> AirportTypes { get; set; }
        public DbSet<Airport> Airports { get; set; }


        // TODO: VC -> BG: Please check if this should exist or should it be deleted?
        internal void EnsureSeedDataForContext()
        {
            throw new NotImplementedException();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            SeedData(modelBuilder);
        }

        private static void SeedData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                            new Country { Id = 1, Name = "Afghanistan", Iso = "AF" },
                            new Country { Id = 2, Name = "Åland Islands", Iso = "AX" },
                            new Country { Id = 3, Name = "Albania", Iso = "AL" },
                            new Country { Id = 4, Name = "Algeria", Iso = "DZ" },
                            new Country { Id = 5, Name = "American Samoa", Iso = "AS" },
                            new Country { Id = 6, Name = "Andorra", Iso = "AD" },
                            new Country { Id = 7, Name = "Angola", Iso = "AO" },
                            new Country { Id = 8, Name = "Anguilla", Iso = "AI" },
                            new Country { Id = 9, Name = "Antarctica", Iso = "AQ" },
                            new Country { Id = 10, Name = "Antigua and Barbuda", Iso = "AG" },
                            new Country { Id = 11, Name = "Argentina", Iso = "AR" },
                            new Country { Id = 12, Name = "Armenia", Iso = "AM" },
                            new Country { Id = 13, Name = "Aruba", Iso = "AW" },
                            new Country { Id = 14, Name = "Australia", Iso = "AU" },
                            new Country { Id = 15, Name = "Austria", Iso = "AT" },
                            new Country { Id = 16, Name = "Azerbaijan", Iso = "AZ" },
                            new Country { Id = 17, Name = "Bahrain", Iso = "BH" },
                            new Country { Id = 18, Name = "Bahamas", Iso = "BS" },
                            new Country { Id = 19, Name = "Bangladesh", Iso = "BD" },
                            new Country { Id = 20, Name = "Barbados", Iso = "BB" },
                            new Country { Id = 21, Name = "Belarus", Iso = "BY" },
                            new Country { Id = 22, Name = "Belgium", Iso = "BE" },
                            new Country { Id = 23, Name = "Belize", Iso = "BZ" },
                            new Country { Id = 24, Name = "Benin", Iso = "BJ" },
                            new Country { Id = 25, Name = "Bermuda", Iso = "BM" },
                            new Country { Id = 26, Name = "Bhutan", Iso = "BT" },
                            new Country { Id = 27, Name = "Bolivia, Plurinational State of", Iso = "BO" },
                            new Country { Id = 28, Name = "Bonaire, Sint Eustatius and Saba", Iso = "BQ" },
                            new Country { Id = 29, Name = "Bosnia and Herzegovina", Iso = "BA" },
                            new Country { Id = 30, Name = "Botswana", Iso = "BW" },
                            new Country { Id = 31, Name = "Bouvet Island", Iso = "BV" },
                            new Country { Id = 32, Name = "Brazil", Iso = "BR" },
                            new Country { Id = 33, Name = "British Indian Ocean Territory", Iso = "IO" },
                            new Country { Id = 34, Name = "Brunei Darussalam", Iso = "BN" },
                            new Country { Id = 35, Name = "Bulgaria", Iso = "BG" },
                            new Country { Id = 36, Name = "Burkina Faso", Iso = "BF" },
                            new Country { Id = 37, Name = "Burundi", Iso = "BI" },
                            new Country { Id = 38, Name = "Cambodia", Iso = "KH" },
                            new Country { Id = 39, Name = "Cameroon", Iso = "CM" },
                            new Country { Id = 40, Name = "Canada", Iso = "CA" },
                            new Country { Id = 41, Name = "Cape Verde", Iso = "CV" },
                            new Country { Id = 42, Name = "Cayman Islands", Iso = "KY" },
                            new Country { Id = 43, Name = "Central African Republic", Iso = "CF" },
                            new Country { Id = 44, Name = "Chad", Iso = "TD" },
                            new Country { Id = 45, Name = "Chile", Iso = "CL" },
                            new Country { Id = 46, Name = "China", Iso = "CN" },
                            new Country { Id = 47, Name = "Christmas Island", Iso = "CX" },
                            new Country { Id = 48, Name = "Cocos (Keeling) Islands", Iso = "CC" },
                            new Country { Id = 49, Name = "Colombia", Iso = "CO" },
                            new Country { Id = 50, Name = "Comoros", Iso = "KM" },
                            new Country { Id = 51, Name = "Congo", Iso = "CG" },
                            new Country { Id = 52, Name = "Congo, the Democratic Republic of the", Iso = "CD" },
                            new Country { Id = 53, Name = "Cook Islands", Iso = "CK" },
                            new Country { Id = 54, Name = "Costa Rica", Iso = "CR" },
                            new Country { Id = 55, Name = "Côte d'Ivoire", Iso = "CI" },
                            new Country { Id = 56, Name = "Croatia", Iso = "HR" },
                            new Country { Id = 57, Name = "Cuba", Iso = "CU" },
                            new Country { Id = 58, Name = "Curaçao", Iso = "CW" },
                            new Country { Id = 59, Name = "Cyprus", Iso = "CY" },
                            new Country { Id = 60, Name = "Czech Republic", Iso = "CZ" },
                            new Country { Id = 61, Name = "Denmark", Iso = "DK" },
                            new Country { Id = 62, Name = "Djibouti", Iso = "DJ" },
                            new Country { Id = 63, Name = "Dominica", Iso = "DM" },
                            new Country { Id = 64, Name = "Dominican Republic", Iso = "DO" },
                            new Country { Id = 65, Name = "Ecuador", Iso = "EC" },
                            new Country { Id = 66, Name = "Egypt", Iso = "EG" },
                            new Country { Id = 67, Name = "El Salvador", Iso = "SV" },
                            new Country { Id = 68, Name = "Equatorial Guinea", Iso = "GQ" },
                            new Country { Id = 69, Name = "Eritrea", Iso = "ER" },
                            new Country { Id = 70, Name = "Estonia", Iso = "EE" },
                            new Country { Id = 71, Name = "Ethiopia", Iso = "ET" },
                            new Country { Id = 72, Name = "Falkland Islands (Malvinas)", Iso = "FK" },
                            new Country { Id = 73, Name = "Faroe Islands", Iso = "FO" },
                            new Country { Id = 74, Name = "Fiji", Iso = "FJ" },
                            new Country { Id = 75, Name = "Finland", Iso = "FI" },
                            new Country { Id = 76, Name = "France", Iso = "FR" },
                            new Country { Id = 77, Name = "French Guiana", Iso = "GF" },
                            new Country { Id = 78, Name = "French Polynesia", Iso = "PF" },
                            new Country { Id = 79, Name = "French Southern Territories", Iso = "TF" },
                            new Country { Id = 80, Name = "Gabon", Iso = "GA" },
                            new Country { Id = 81, Name = "Gambia", Iso = "GM" },
                            new Country { Id = 82, Name = "Georgia", Iso = "GE" },
                            new Country { Id = 83, Name = "Germany", Iso = "DE" },
                            new Country { Id = 84, Name = "Ghana", Iso = "GH" },
                            new Country { Id = 85, Name = "Gibraltar", Iso = "GI" },
                            new Country { Id = 86, Name = "Greece", Iso = "GR" },
                            new Country { Id = 87, Name = "Greenland", Iso = "GL" },
                            new Country { Id = 88, Name = "Grenada", Iso = "GD" },
                            new Country { Id = 89, Name = "Guadeloupe", Iso = "GP" },
                            new Country { Id = 90, Name = "Guam", Iso = "GU" },
                            new Country { Id = 91, Name = "Guatemala", Iso = "GT" },
                            new Country { Id = 92, Name = "Guernsey", Iso = "GG" },
                            new Country { Id = 93, Name = "Guinea", Iso = "GN" },
                            new Country { Id = 94, Name = "Guinea-Bissau", Iso = "GW" },
                            new Country { Id = 95, Name = "Guyana", Iso = "GY" },
                            new Country { Id = 96, Name = "Haiti", Iso = "HT" },
                            new Country { Id = 97, Name = "Heard Island and McDonald Islands", Iso = "HM" },
                            new Country { Id = 98, Name = "Holy See (Vatican City State)", Iso = "VA" },
                            new Country { Id = 99, Name = "Honduras", Iso = "HN" },
                            new Country { Id = 100, Name = "Hong Kong", Iso = "HK" },
                            new Country { Id = 101, Name = "Hungary", Iso = "HU" },
                            new Country { Id = 102, Name = "Iceland", Iso = "IS" },
                            new Country { Id = 103, Name = "India", Iso = "IN" },
                            new Country { Id = 104, Name = "Indonesia", Iso = "ID" },
                            new Country { Id = 105, Name = "Iran, Islamic Republic of", Iso = "IR" },
                            new Country { Id = 106, Name = "Iraq", Iso = "IQ" },
                            new Country { Id = 107, Name = "Ireland", Iso = "IE" },
                            new Country { Id = 108, Name = "Isle of Man", Iso = "IM" },
                            new Country { Id = 109, Name = "Israel", Iso = "IL" },
                            new Country { Id = 110, Name = "Italy", Iso = "IT" },
                            new Country { Id = 111, Name = "Jamaica", Iso = "JM" },
                            new Country { Id = 112, Name = "Japan", Iso = "JP" },
                            new Country { Id = 113, Name = "Jersey", Iso = "JE" },
                            new Country { Id = 114, Name = "Jordan", Iso = "JO" },
                            new Country { Id = 115, Name = "Kazakhstan", Iso = "KZ" },
                            new Country { Id = 116, Name = "Kenya", Iso = "KE" },
                            new Country { Id = 117, Name = "Kiribati", Iso = "KI" },
                            new Country { Id = 118, Name = "Korea, Democratic People's Republic of", Iso = "KP" },
                            new Country { Id = 119, Name = "Korea, Republic of", Iso = "KR" },
                            new Country { Id = 120, Name = "Kuwait", Iso = "KW" },
                            new Country { Id = 121, Name = "Kyrgyzstan", Iso = "KG" },
                            new Country { Id = 122, Name = "Lao People's Democratic Republic", Iso = "LA" },
                            new Country { Id = 123, Name = "Latvia", Iso = "LV" },
                            new Country { Id = 124, Name = "Lebanon", Iso = "LB" },
                            new Country { Id = 125, Name = "Lesotho", Iso = "LS" },
                            new Country { Id = 126, Name = "Liberia", Iso = "LR" },
                            new Country { Id = 127, Name = "Libya", Iso = "LY" },
                            new Country { Id = 128, Name = "Liechtenstein", Iso = "LI" },
                            new Country { Id = 129, Name = "Lithuania", Iso = "LT" },
                            new Country { Id = 130, Name = "Luxembourg", Iso = "LU" },
                            new Country { Id = 131, Name = "Macao", Iso = "MO" },
                            new Country { Id = 132, Name = "Macedonia, the Former Yugoslav Republic of", Iso = "MK" },
                            new Country { Id = 133, Name = "Madagascar", Iso = "MG" },
                            new Country { Id = 134, Name = "Malawi", Iso = "MW" },
                            new Country { Id = 135, Name = "Malaysia", Iso = "MY" },
                            new Country { Id = 136, Name = "Maldives", Iso = "MV" },
                            new Country { Id = 137, Name = "Mali", Iso = "ML" },
                            new Country { Id = 138, Name = "Malta", Iso = "MT" },
                            new Country { Id = 139, Name = "Marshall Islands", Iso = "MH" },
                            new Country { Id = 140, Name = "Martinique", Iso = "MQ" },
                            new Country { Id = 141, Name = "Mauritania", Iso = "MR" },
                            new Country { Id = 142, Name = "Mauritius", Iso = "MU" },
                            new Country { Id = 143, Name = "Mayotte", Iso = "YT" },
                            new Country { Id = 144, Name = "Mexico", Iso = "MX" },
                            new Country { Id = 145, Name = "Micronesia, Federated States of", Iso = "FM" },
                            new Country { Id = 146, Name = "Moldova, Republic of", Iso = "MD" },
                            new Country { Id = 147, Name = "Monaco", Iso = "MC" },
                            new Country { Id = 148, Name = "Mongolia", Iso = "MN" },
                            new Country { Id = 149, Name = "Montenegro", Iso = "ME" },
                            new Country { Id = 150, Name = "Montserrat", Iso = "MS" },
                            new Country { Id = 151, Name = "Morocco", Iso = "MA" },
                            new Country { Id = 152, Name = "Mozambique", Iso = "MZ" },
                            new Country { Id = 153, Name = "Myanmar", Iso = "MM" },
                            new Country { Id = 154, Name = "Namibia", Iso = "NA" },
                            new Country { Id = 155, Name = "Nauru", Iso = "NR" },
                            new Country { Id = 156, Name = "Nepal", Iso = "NP" },
                            new Country { Id = 157, Name = "Netherlands", Iso = "NL" },
                            new Country { Id = 158, Name = "New Caledonia", Iso = "NC" },
                            new Country { Id = 159, Name = "New Zealand", Iso = "NZ" },
                            new Country { Id = 160, Name = "Nicaragua", Iso = "NI" },
                            new Country { Id = 161, Name = "Niger", Iso = "NE" },
                            new Country { Id = 162, Name = "Nigeria", Iso = "NG" },
                            new Country { Id = 163, Name = "Niue", Iso = "NU" },
                            new Country { Id = 164, Name = "Norfolk Island", Iso = "NF" },
                            new Country { Id = 165, Name = "Northern Mariana Islands", Iso = "MP" },
                            new Country { Id = 166, Name = "Norway", Iso = "NO" },
                            new Country { Id = 167, Name = "Oman", Iso = "OM" },
                            new Country { Id = 168, Name = "Pakistan", Iso = "PK" },
                            new Country { Id = 169, Name = "Palau", Iso = "PW" },
                            new Country { Id = 170, Name = "Palestine, State of", Iso = "PS" },
                            new Country { Id = 171, Name = "Panama", Iso = "PA" },
                            new Country { Id = 172, Name = "Papua New Guinea", Iso = "PG" },
                            new Country { Id = 173, Name = "Paraguay", Iso = "PY" },
                            new Country { Id = 174, Name = "Peru", Iso = "PE" },
                            new Country { Id = 175, Name = "Philippines", Iso = "PH" },
                            new Country { Id = 176, Name = "Pitcairn", Iso = "PN" },
                            new Country { Id = 177, Name = "Poland", Iso = "PL" },
                            new Country { Id = 178, Name = "Portugal", Iso = "PT" },
                            new Country { Id = 179, Name = "Puerto Rico", Iso = "PR" },
                            new Country { Id = 180, Name = "Qatar", Iso = "QA" },
                            new Country { Id = 181, Name = "Réunion", Iso = "RE" },
                            new Country { Id = 182, Name = "Romania", Iso = "RO" },
                            new Country { Id = 183, Name = "Russian Federation", Iso = "RU" },
                            new Country { Id = 184, Name = "Rwanda", Iso = "RW" },
                            new Country { Id = 185, Name = "Saint Barthélemy", Iso = "BL" },
                            new Country { Id = 186, Name = "Saint Helena, Ascension and Tristan da Cunha", Iso = "SH" },
                            new Country { Id = 187, Name = "Saint Kitts and Nevis", Iso = "KN" },
                            new Country { Id = 188, Name = "Saint Lucia", Iso = "LC" },
                            new Country { Id = 189, Name = "Saint Martin (French part)", Iso = "MF" },
                            new Country { Id = 190, Name = "Saint Pierre and Miquelon", Iso = "PM" },
                            new Country { Id = 191, Name = "Saint Vincent and the Grenadines", Iso = "VC" },
                            new Country { Id = 192, Name = "Samoa", Iso = "WS" },
                            new Country { Id = 193, Name = "San Marino", Iso = "SM" },
                            new Country { Id = 194, Name = "Sao Tome and Principe", Iso = "ST" },
                            new Country { Id = 195, Name = "Saudi Arabia", Iso = "SA" },
                            new Country { Id = 196, Name = "Senegal", Iso = "SN" },
                            new Country { Id = 197, Name = "Serbia", Iso = "RS" },
                            new Country { Id = 198, Name = "Seychelles", Iso = "SC" },
                            new Country { Id = 199, Name = "Sierra Leone", Iso = "SL" },
                            new Country { Id = 200, Name = "Singapore", Iso = "SG" },
                            new Country { Id = 201, Name = "Sint Maarten (Dutch part)", Iso = "SX" },
                            new Country { Id = 202, Name = "Slovakia", Iso = "SK" },
                            new Country { Id = 203, Name = "Slovenia", Iso = "SI" },
                            new Country { Id = 204, Name = "Solomon Islands", Iso = "SB" },
                            new Country { Id = 205, Name = "Somalia", Iso = "SO" },
                            new Country { Id = 206, Name = "South Africa", Iso = "ZA" },
                            new Country { Id = 207, Name = "South Georgia and the South Sandwich Islands", Iso = "GS" },
                            new Country { Id = 208, Name = "South Sudan", Iso = "SS" },
                            new Country { Id = 209, Name = "Spain", Iso = "ES" },
                            new Country { Id = 210, Name = "Sri Lanka", Iso = "LK" },
                            new Country { Id = 211, Name = "Sudan", Iso = "SD" },
                            new Country { Id = 212, Name = "Suriname", Iso = "SR" },
                            new Country { Id = 213, Name = "Svalbard and Jan Mayen", Iso = "SJ" },
                            new Country { Id = 214, Name = "Swaziland", Iso = "SZ" },
                            new Country { Id = 215, Name = "Sweden", Iso = "SE" },
                            new Country { Id = 216, Name = "Switzerland", Iso = "CH" },
                            new Country { Id = 217, Name = "Syrian Arab Republic", Iso = "SY" },
                            new Country { Id = 218, Name = "Taiwan, Province of China", Iso = "TW" },
                            new Country { Id = 219, Name = "Tajikistan", Iso = "TJ" },
                            new Country { Id = 220, Name = "Tanzania, United Republic of", Iso = "TZ" },
                            new Country { Id = 221, Name = "Thailand", Iso = "TH" },
                            new Country { Id = 222, Name = "Timor-Leste", Iso = "TL" },
                            new Country { Id = 223, Name = "Togo", Iso = "TG" },
                            new Country { Id = 224, Name = "Tokelau", Iso = "TK" },
                            new Country { Id = 225, Name = "Tonga", Iso = "TO" },
                            new Country { Id = 226, Name = "Trinidad and Tobago", Iso = "TT" },
                            new Country { Id = 227, Name = "Tunisia", Iso = "TN" },
                            new Country { Id = 228, Name = "Turkey", Iso = "TR" },
                            new Country { Id = 229, Name = "Turkmenistan", Iso = "TM" },
                            new Country { Id = 230, Name = "Turks and Caicos Islands", Iso = "TC" },
                            new Country { Id = 231, Name = "Tuvalu", Iso = "TV" },
                            new Country { Id = 232, Name = "Uganda", Iso = "UG" },
                            new Country { Id = 233, Name = "Ukraine", Iso = "UA" },
                            new Country { Id = 234, Name = "United Arab Emirates", Iso = "AE" },
                            new Country { Id = 235, Name = "United Kingdom", Iso = "GB" },
                            new Country { Id = 236, Name = "United States", Iso = "US" },
                            new Country { Id = 237, Name = "United States Minor Outlying Islands", Iso = "UM" },
                            new Country { Id = 238, Name = "Uruguay", Iso = "UY" },
                            new Country { Id = 239, Name = "Uzbekistan", Iso = "UZ" },
                            new Country { Id = 240, Name = "Vanuatu", Iso = "VU" },
                            new Country { Id = 241, Name = "Venezuela, Bolivarian Republic of", Iso = "VE" },
                            new Country { Id = 242, Name = "Viet Nam", Iso = "VN" },
                            new Country { Id = 243, Name = "Virgin Islands, British", Iso = "VG" },
                            new Country { Id = 244, Name = "Virgin Islands, U.S.", Iso = "VI" },
                            new Country { Id = 245, Name = "Wallis and Futuna", Iso = "WF" },
                            new Country { Id = 246, Name = "Western Sahara", Iso = "EH" },
                            new Country { Id = 247, Name = "Yemen", Iso = "YE" },
                            new Country { Id = 248, Name = "Zambia", Iso = "ZM" },
                            new Country { Id = 249, Name = "Zimbabwe", Iso = "ZW" });
        }
    }
}
